---
kind: Template
apiVersion: v1
metadata:
  annotations:
    iconClass: icon-jboss
    description: Application template for Eclipse Vert.x REST + Red Hat SSO demo application.
    tags: javaee,java,jboss,xpaas,sso
    version: 1.3.2
  name: secured-vertx-http
labels:
  template: secured-vertx-http
  xpaas: 1.3.2
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  value: secured-vertx-http
  required: true
- description: 'Custom hostname for http service route.  Leave blank for default hostname,
    e.g.: <application-name>-<project>.<default-domain-suffix>'
  name: HOSTNAME_HTTP
  value: ''
  required: false
- description: The URL for the SSO server (e.g. https://secure-sso-myproject.example.com/auth).  This
    is the URL through which the user will be redirected when a login or token is
    required by the application.
  name: SSO_AUTH_SERVER_URL
  value: ${SSO_AUTH_SERVER_URL}
  required: true
- description: The RH-SSO realm to be used.
  name: REALM
  value: master
  required: true
- description: Realm's public key.
  name: REALM_PUBLIC_KEY
  value: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoETnPmN55xBJjRzN/cs30OzJ9olkteLVNRjzdTxFOyRtS2ovDfzdhhO9XzUcTMbIsCOAZtSt8K+6yvBXypOSYvI75EUdypmkcK1KoptqY5KEBQ1KwhWuP7IWQ0fshUwD6jI1QWDfGxfM/h34FvEn/0tJ71xN2P8TI2YanwuDZgosdobx/PAvlGREBGuk4BgmexTOkAdnFxIUQcCkiEZ2C41uCrxiS4CEe5OX91aK9HKZV4ZJX6vnqMHmdDnsMdO+UFtxOBYZio+a1jP4W3d7J5fGeiOaXjQCOpivKnP2yU2DPdWmDMyVb67l8DRA+jh0OJFKZ5H2fNgE3II59vdsRwIDAQAB
  required: true
- description: RH-SSO client id.
  name: CLIENT_ID
  value: demoapp
  required: true
- description: RH-SSO secret.
  name: SECRET
  value: 1daa57a2-b60e-468b-a3ac-25bd2dc2eadc
  required: true
