apiVersion: v1
kind: Service
metadata:
  name: secured-vertx-rest
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentConfig: secured-vertx-rest
